NIL_TEXTURE = SF::Texture.new(672, 1024)

#WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
#W                                         Wood Textures                                             W
#WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
 WOOD_TEXTURE_01 = SF::Texture.from_file("../graphics/Wood01.png");

#SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
#S                                         Skin Textures                                             S
#SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS

 PALE_SKIN_TEXTURE = SF::Texture.from_file("../graphics/Char_Skin.png")

 TAN_SKIN_TEXTURE = SF::Texture.from_file("../graphics/Char_Skin_Tan.png")

 DARK_SKIN_TEXTURE = SF::Texture.from_file("../graphics/Char_Skin_Dark.png")

 GHOSTLY_SKIN_TEXTURE = SF::Texture.from_file("../graphics/Char_Skin_Ghostly.png")

 JAUNDICED_SKIN_TEXTURE = SF::Texture.from_file("../graphics/Char_Skin_Jaundiced.png")

 BLUE_SKIN_TEXTURE = SF::Texture.from_file("../graphics/Char_Skin_Blue.png")
 
 PINK_SKIN_TEXTURE = SF::Texture.from_file("../graphics/Char_Skin_Pink.png")

 GREEN_SKIN_TEXTURE = SF::Texture.from_file("../graphics/Char_Skin_Green.png")

 PURPLE_SKIN_TEXTURE = SF::Texture.from_file("../graphics/Char_Skin_Purple.png")

 RED_SKIN_TEXTURE = SF::Texture.from_file("../graphics/Char_Skin_Red.png")

#HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH
#H                                         Hair Textures                                             H
#HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH
 #White Shounen Skin
 SHOUNEN_HAIR_WHITE_TEXTURE = SF::Texture.from_file("../graphics/White_Shounen_Hair.png")
 #Black Shounen Skin
 SHOUNEN_HAIR_BLACK_TEXTURE = SF::Texture.from_file("../graphics/Black_Shounen_Hair.png")

 #FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
 #F                                        Face Textures                                             F
 #FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF

  BUTTON_EYES_BLUE_TEXTURE = SF::Texture.from_file("../graphics/Blue_Button_Eyes.png")

  BUTTON_EYES_BLACK_TEXTURE = SF::Texture.from_file("../graphics/Black_Button_Eyes.png")

 #PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
 #P                                        Pants Textures                                            P
 #PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
  JEANS_WHITE_TEXTURE = SF::Texture.from_file("../graphics/White_Jeans.png")

  JEANS_BLACK_TEXTURE = SF::Texture.from_file("../graphics/Black_Jeans.png")

 #SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
 #S                                         Shirt Textures                                           S
 #SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS

  TANK_TOP_WHITE_TEXTURE = SF::Texture.from_file("../graphics/White_Tank_Top.png")

  TANK_TOP_BLACK_TEXTURE = SF::Texture.from_file("../graphics/Black_Tank_Top.png")

  TANK_TOP_ORANGE_TEXTURE = SF::Texture.from_file("../graphics/Orange_Tank_Top.png")

 #SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
 #S                                          Shoe Textures                                           S
 #SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
  RAIN_BOOTS_WHITE_TEXTURE = SF::Texture.from_file("../graphics/White_Rain_Boots.png")

  RAIN_BOOTS_BLACK_TEXTURE = SF::Texture.from_file("../graphics/Black_Rain_Boots.png")

 #GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
 #G                                         Glove Textures                                           G
 #GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
  FINGERLESS_GLOVES_WHITE_TEXTURE = SF::Texture.from_file("../graphics/White_Fingerless_Gloves.png")

 #WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
 #W                                         Weapon Textures                                          W
 #WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
  WOODEN_STICK_TEXTURE = SF::Texture.from_file("../graphics/Wooden_Stick.png") 